# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: BuildMacOSXWithSonarQube
  displayName: Build for MacOSX With SonarQube
  dependsOn: [] # by specifying an empty array, this stage doesn't depend on the stage before it
  pool:
    vmImage: 'macOS-latest'
  variables:
    CC: clang
    CXX: clang++
  steps:
  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'Peach'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'geoffray-azure-xcodebuild-macosx-test'
      cliProjectName: 'geoffray-azure-xcodebuild-macosx-test'
      cliSources: 'sonar_scanner_example'
      extraProperties: 'sonar.cfamily.build-wrapper-output=build_wrapper_output_directory'
  - bash: |
      curl 'https://peach.sonarsource.com/static/cpp/build-wrapper-macosx-x86.zip' --output build-wrapper-macosx-x86.zip
      unzip build-wrapper-macosx-x86.zip
    displayName: Install buildwrapper
  - bash: |
      xcodebuild -project sonar_scanner_example.xcodeproj clean
    workingDirectory: .
    displayName: Prepare build
  - bash: |
      build-wrapper-macosx-x86/build-wrapper-macosx-x86 --out-dir build_wrapper_output_directory xcodebuild -project sonar_scanner_example.xcodeproj -configuration Release
    displayName: Compile project in build wrapper
  - task: SonarQubeAnalyze@4

- job: BuildMacOSXWithSonarCloud
  displayName: Build for MacOSX With SonarCloud
  dependsOn: [] # by specifying an empty array, this stage doesn't depend on the stage before it
  pool:
    vmImage: 'macOS-latest'
  variables:
    CC: clang
    CXX: clang++
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'geoffray-adde-sonarsource-github'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'geoffray-azure-xcodebuild-macosx-test'
      cliProjectName: 'geoffray-azure-xcodebuild-macosx-test'
      cliSources: 'sonar_scanner_example'
      extraProperties: 'sonar.cfamily.build-wrapper-output=build_wrapper_output_directory'
  - bash: |
      curl 'https://peach.sonarsource.com/static/cpp/build-wrapper-macosx-x86.zip' --output build-wrapper-macosx-x86.zip
      unzip build-wrapper-macosx-x86.zip
    displayName: Install buildwrapper
  - bash: |
      xcodebuild -project sonar_scanner_example.xcodeproj clean
    workingDirectory: .
    displayName: Prepare build
  - bash: |
      build-wrapper-macosx-x86/build-wrapper-macosx-x86 --out-dir build_wrapper_output_directory xcodebuild -project sonar_scanner_example.xcodeproj -configuration Release
    displayName: Compile project in build wrapper
  - task: SonarCloudAnalyze@1